substitutions:
  name: esp32-s3-box
  friendly_name: BoxS3
  loading_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/loading_320_240.png
  idle_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/idle_320_240.png
  listening_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/listening_320_240.png
  thinking_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/thinking_320_240.png
  replying_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/replying_320_240.png
  error_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/error_320_240.png
  timer_finished_illustration_file: https://raw.githubusercontent.com/thesavant42/wake-word-voice-assistants/refs/heads/main/stickerbox/timer_finished_320_240.png
  loading_illustration_background_color: '000000'
  idle_illustration_background_color: '000000'
  listening_illustration_background_color: '000000'
  thinking_illustration_background_color: '000000'
  replying_illustration_background_color: '000000'
  error_illustration_background_color: '000000'

packages:
  esphome.voice-assistant: github://thesavant42/wake-word-voice-assistants/esp32-s3-box/esp32-s3-box.yaml

# Corrected top-level entry for micro_wake_word
micro_wake_word:
  vad:
    model: github://esphome/micro-wake-word-models/models/v2/vad.json
  models:
    # This will ADD your model to the list of models in the included package
    - model: https://raw.githubusercontent.com/thesavant42/microWakeWord-Trainer-Nvidia-Docker/refs/heads/main/mww_savant42/master_yoda.json

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
    platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
    board_build.cmake_extra_args: "-DIDF_COMPONENT_MANAGER=OFF"

api:
  encryption:
    key: udWs3pP3okbetZZXk3K5dlRhYN/Q1PIslJkcaCEVjWY=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
